return {
	RemoteName = "Audio_PlayLocal",
	MusicPoolFolderName = "MusicPool",

	SoundGroupNames = {
		Music = "MegaRoblox_Music",
		Effects = "MegaRoblox_Effects",
		Environment = "MegaRoblox_Environment",
		Interface = "MegaRoblox_Interface",
	},

	DefaultVolumes = {
		Master = 1,
		Music = 0.55,
		Effects = 0.82,
		Environment = 0.7,
		Interface = 0.72,
	},

	SoundEffects = {
		FireballCast = {
			SoundId = "rbxassetid://9117987278",
			Category = "Effects",
			Volume = 0.42,
			Lifetime = 3,
		},
		JarBreak = {
			SoundId = "rbxassetid://9114498899",
			Category = "Effects",
			Volume = 0.75,
			Lifetime = 4,
		},
		ChestOpen = {
			SoundId = "rbxassetid://5021926317",
			Category = "Effects",
			Volume = 0.78,
			Lifetime = 4,
		},
		RewardChestSpawn = {
			SoundId = "rbxassetid://5021926317",
			Category = "Effects",
			Volume = 0.78,
			Lifetime = 4,
		},
		ShrineCharge = {
			SoundId = "rbxassetid://140576516515813",
			Category = "Effects",
			Volume = 0.55,
			Looped = true,
		},
		ShrineComplete = {
			SoundId = "rbxassetid://123179124316015",
			Category = "Effects",
			Volume = 0.8,
			Lifetime = 4,
		},
		ShrineEliteComplete = {
			SoundId = "rbxassetid://9043352093",
			Category = "Effects",
			Volume = 0.8,
			Lifetime = 4,
		},
		BossArrival = {
			SoundId = "",
			Category = "Effects",
			Volume = 0.8,
			Lifetime = 8,
		},
	},
}
