--!strict

return {
	Characters = {
		medivh = {
			Id = "medivh",
			DefaultSkinId = "medivh_default",
			Skins = {
				{
					Id = "medivh_default",
					Name = "Velours arcanique",
					Description = "Tenue de mage nocturne.",
					Image = "rbxassetid://72675265292172",
					UnlockType = "Starter",
					Clothing = {
						ShirtTemplate = "rbxassetid://109688448865927",
						PantsTemplate = "rbxassetid://105765423035091",
						MaterialSet = "MedivhArcaneV1",
					},
				},
			},
		},
		albert = {
			Id = "albert",
			DefaultSkinId = "albert_default",
			Skins = {
				{
					Id = "albert_default",
					Name = "Atelier galvanique",
					Description = "Tenue de laboratoire renforcee.",
					Image = "rbxassetid://76272865710318",
					UnlockType = "Starter",
					Clothing = {
						ShirtTemplate = "rbxassetid://100088502706587",
						PantsTemplate = "rbxassetid://123980013567477",
						MaterialSet = "AlbertLaboratoryV1",
					},
				},
			},
		},
		shinobi = {
			Id = "shinobi",
			DefaultSkinId = "shinobi_shadow",
			Skins = {
				{
					Id = "shinobi_shadow",
					Name = "Shinobi de l'ombre",
					Description = "Tenue furtive de tissu sombre et d'accents violets.",
					Image = "rbxassetid://104698571348162",
					UnlockType = "Starter",
					Clothing = {
						ShirtTemplate = "rbxassetid://81502804062973",
						PantsTemplate = "rbxassetid://127826973384729",
						MaterialSet = "ShinobiShadowV1",
					},
				},
			},
		},
		rusal_gale = {
			Id = "rusal_gale",
			DefaultSkinId = "rusal_gale_default",
			Skins = {
				{
					Id = "rusal_gale_default",
					Name = "Veilleur des ames",
					Description = "Robe funeraire, os anciens et runes d'ames emeraude.",
					Image = "rbxassetid://111222772217752",
					UnlockType = "Starter",
					Clothing = {
						ShirtTemplate = "rbxassetid://140150101017634",
						PantsTemplate = "rbxassetid://88177762501851",
						MaterialSet = "RusalGaleNecromanticV1",
					},
				},
			},
		},
		rufus = {
			Id = "rufus",
			DefaultSkinId = "rufus_valorcrest",
			Skins = {
				{
					Id = "rufus_valorcrest",
					Name = "Bastion de Valorcrest",
					Description = "Acier royal, drap bleu profond et liseres dores.",
					Image = "rbxassetid://117769701520930",
					UnlockType = "Starter",
					Clothing = {
						ShirtTemplate = "rbxassetid://128402560504693",
						PantsTemplate = "rbxassetid://112987301949770",
						MaterialSet = "RufusValorcrestV1",
					},
				},
			},
		},
		lorelei = {
			Id = "lorelei",
			DefaultSkinId = "lorelei_nightveil",
			Skins = {
				{
					Id = "lorelei_nightveil",
					Name = "Voile nocturne",
					Description = "Acier d'obsidienne, velours bordeaux et cristaux de vie magenta.",
					Image = "rbxassetid://110000926797342",
					UnlockType = "Starter",
					Clothing = {
						ShirtTemplate = "rbxassetid://73217425125133",
						PantsTemplate = "rbxassetid://73217425125133",
						MaterialSet = "LoreleiNightveilV1",
					},
				},
			},
		},
	},
}
