return {
	UpdateInterval = 0.18,
	PanelOffset = Vector2.new(16, 128),
	PanelSize = Vector2.new(184, 184),
	MinimumScale = 0.72,
	MaximumScale = 1,
	VisibleRadius = 135,
	MarkerSize = 8,
	PlayerMarkerSize = 10,
	MarkerPadding = 7,
	GridLineCount = 4,

	Colors = {
		Player = Color3.fromRGB(228, 249, 255),
		Portal = Color3.fromRGB(213, 105, 255),
		PerkShrine = Color3.fromRGB(166, 111, 255),
		MagnetShrine = Color3.fromRGB(50, 236, 255),
		EliteShrine = Color3.fromRGB(255, 89, 89),
		Chest = Color3.fromRGB(255, 204, 70),
		Jar = Color3.fromRGB(198, 156, 112),
		Totem = Color3.fromRGB(255, 130, 54),
	},
}
