return {
	Weapons = {
		fireball = {
			Id = "fireball",
			Name = "Fireball",
			Description = "Arme automatique de depart.",
			Icon = "rbxassetid://91848234123005",
			DefaultSkinId = "fireball_default",
			Skins = {
				{
					Id = "fireball_default",
					Name = "Boule de feu classique",
					Description = "Apparence de base du projectile.",
					Image = "rbxassetid://91848234123005",
					UnlockType = "Starter",
					VfxProfileId = "fireball_default",
				},
				{
					Id = "fireball_arcane",
					Name = "Boule de feu arcanique",
					Description = "Premier skin de projectile arcane.",
					Image = "rbxassetid://71084954582713",
					UnlockType = "Starter",
					VfxProfileId = "fireball_arcane",
				},
			},
		},
	},
}
