return {
	Weapons = {
		fireball = {
			Id = "fireball",
			Name = "Fireball",
			Description = "Arme automatique de depart.",
			Icon = "rbxassetid://91848234123005",
			DefaultSkinId = "fireball_default",
			Skins = {
				{
					Id = "fireball_default",
					Name = "Boule de feu classique",
					Description = "Apparence de base du projectile.",
					Image = "rbxassetid://91848234123005",
					UnlockType = "Starter",
					VfxProfileId = "fireball_default",
				},
				{
					Id = "fireball_arcane",
					Name = "Boule de feu arcanique",
					Description = "Premier skin de projectile arcane.",
					Image = "rbxassetid://71084954582713",
					UnlockType = "Starter",
					VfxProfileId = "fireball_arcane",
				},
			},
		},
		shuriken = {
			Id = "shuriken",
			Name = "Shuriken",
			Description = "Etoiles de jet automatiques en cone.",
			Icon = "rbxassetid://82295159291408",
			DefaultSkinId = "shuriken_shadowspin",
			Skins = {
				{
					Id = "shuriken_shadowspin",
					Name = "Shadowspin",
					Description = "Obsidienne et energie violette.",
					Image = "rbxassetid://82295159291408",
					UnlockType = "Starter",
					VfxProfileId = "shuriken_shadowspin",
				},
				{
					Id = "shuriken_moonveil",
					Name = "Moonveil",
					Description = "Acier lunaire et energie cyan.",
					Image = "rbxassetid://137477216660458",
					UnlockType = "Starter",
					VfxProfileId = "shuriken_moonveil",
				},
			},
		},
		soul_lantern = {
			Id = "soul_lantern",
			Name = "Lanterne des ames",
			Description = "Lanterne spectrale qui appelle les revenants.",
			Icon = "rbxassetid://97347879630224",
			DefaultSkinId = "soul_lantern_default",
			Skins = {
				{
					Id = "soul_lantern_default",
					Name = "Veille funeraire",
					Description = "Lueur emeraude et acier patine.",
					Image = "rbxassetid://97347879630224",
					UnlockType = "Starter",
					VfxProfileId = "SoulLanternSummon",
				},
			},
		},
	},
}
